name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
      - name: Import Submoudles
        uses: actions/checkout@v1

      - name: Compile
        run: sbt compile

      - name: TestPlain
        run: sbt test
